baseURL = "https://annaba.tech/"
languageCode = "en-us"
title = "Annaba Tech Day"
theme = "sarah"

[params]
author = "Annaba Tech Day Team"
slogan = "Practical Workshops Around Programming, Engineering, Devops, Design, Workflows and more.."
keywords = ["annaba", "tech", "dev", "programming", "algeria", "يرمجة", "عنابة", "workshop"]
avatar = "images/palais_culture.jpg"
dateform = "2018-01-29"
lang = "en"
footertext = "Annaba Tech Day Team"
googleAnalytics = ""
about = """
Annaba Tech, a community-driven initiative that promotes tech, focused workshops and meetups around everything software development, engineering, design, security ..etc. We hope we can gather Annabi students and software developers and bring them together to discuss and share interesting topics.
"""

[params.social]
twitter       = "https://twitter.com/AnnabaTech"
youtube       = "https://www.youtube.com/channel/UCEir2tStcVIR-tQaI95Tp8Q"
facebook      = "https://facebook.com/annabatechday"
github        = "https://github.com/annaba-tech"

[[params.info]]
label = "Address"
value = "Palais de la culture, Annaba"

[[params.projects]]
name = "Discovering Python - A Sneaky Snake that you might want to embrace as developer / tech agency in Algeria"
desc = "A workshop to discover Python programming language, its ecosystem, web frameworks and how Python can be a great choice when it comes to simplicity and developers productivity."
img = "images/workshops/python.png"
link = "https://www.python.org/"

[[params.projects]]
name = "Discovering Flutter as a viable cross-platform mobile app development SDK from Google"
desc = "Flutter is a new SDK from Google, recently got to version 1.0. Raouf Rahiche will present how powerful and limitless is Flutter as a mobile development tool."
img = "images/workshops/flutter.png"
link = "https://flutter.io"

[[params.projects]]
name = "Git Basics - Why you should use a version control system within your project"
desc = "Running your project without a version control system is like driving without seatbelt. Walid Ziouche will run this workshop, focusing on Git, starting from scratch with the basics."
img = "images/workshops/git.png"
link = "https://git-scm.com/"

[[params.projects]]
name = "Implementing Domain Driven Design with PHP"
desc = "Sounds scary? no worries, Cherif Bouchelaghem will show how Domain Driven Design is not that weirdo or scary, and how you, as a fresh engineer / student can make use of it to architect better software solutions."
img = "images/workshops/php.png"
link = "https://www.youtube.com/channel/UCZCoLtEGz3MdvxgFhbdZ-QA/featured"

[[params.projects]]
name = "Universal (Isomorphic) Javascript applications with DoneJS"
desc = "Right from one of the core developers of DoneJS, Cherif Bouchelaghem will once again present what DoneJS is, and how to get things done at the frontend side of your web projects, with a universal (isomorphic) JS application as an example."
img = "images/workshops/js.png"
link = "https://donejs.com/"

[[params.projects]]
name = "How to help choose your Stack"
desc = "The tough decition of choosing a tech stack? we've all been there. This is a discussion-based workshop that tries to make it a little bit easier for product managers to help them choose the software stack based on the available humain resources and project requirements. Will be animated by Walid Ziouche."
img = "images/workshops/stack.png"
link = "https://en.wikipedia.org/wiki/Solution_stack"